name: Docker Image CI

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types: 
      - completed

jobs:
  build-images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: tag de version
      run: echo "UNIQUE_TAG=$(date +%s)" >> $GITHUB_ENV
    - name: build the docker image
      run: |
            cd Pass-List-App
            docker build . --file dockerFile_2 --tag nodejs-app-agr:$UNIQUE_TAG
    - name: Push Image to ACR
      run: |
            docker login -u ${{secrets.TOKEN_NAME}} -p ${{secrets.ACR_TOKEN_VALUE}} students.azurecr.io
            docker pushj student.azurecr.io/nodejs-app-agr:$UNIQUE_TAG
            
  
