name: Docker Image CI

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types: 
      - completed

jobs:
  build-images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: tag de version
      run: echo "UNIQUE_TAG=$(date +%s)" >> $GITHUB_ENV
    - name: build the docker image
      run: |
            cd Pass-List-App
            docker build . --file dockerFile_2 --tag nodejs-app-agr:$UNIQUE_TAG
    - name: verificar imagen
      run: docker images
    - name: instalar docker scout
      run: |
            docker login -u vn00uu4 dckr_pat_ShlcstjqwKv21cGY2M3JCuK17_Q students.azurecr.io
            curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
            sh install-scout.sh
    - name: analisis de vulnerabilidades
      run: |  
            docker scout cves student.azurecr.io/nodejs-app-agr:$UNIQUE_TAG
    - name: Push Image to ACR
      run: |
            docker login -u ${{secrets.TOKEN_NAME}} -p ${{secrets.ACR_TOKEN_VALUE}} students.azurecr.io
            docker pushj student.azurecr.io/nodejs-app-agr:$UNIQUE_TAG
            
  
