name: Docker Image CI

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types: 
      - completed

jobs:
  build-images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: tag de version
      run: echo "UNIQUE_TAG=$(date +%s)" >> $GITHUB_ENV
    - name: build the docker image
      run: |
            cd Pass-List-App
            docker build . --file dockerFile_2 --tag node.js-app-agr:$UNIQUE_TAG
    - name: verificar imagen
      run: docker images
    - name: Push Image to ACR
      run: |
            docker  login -u ${{secret.TOKEN_NAME}} -p ${{secret.ACR_TOKEN_VALUE}} students.azurecr.io
            docker pushj studemt.azurecr.io/node.js-app-agr:$UNIQUE_TAG
            
  
